### PR TITLE
Implementing GA4GH service-info in TRS

### LINKED ISSUE #118: Implement service-info
https://github.com/ga4gh-discovery/ga4gh-service-info#how-to-use-and-extend-this-specification

Suggestion in workstream call is to create a PR but leave it pending discussion of loose ends

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-31)
┆containerName: GA4GH tool-registry-service
┆Issue Number: TRS-31

### PR DESCRIPTION
**Pull request by susheel**
Resolves #118

### CODE REVIEW

**Comment by susheel** [comment]
Rebased PR to release/v2.0.1

**Comment by briandoconnor** [comment]
Great to see this!  Thanks @susheel !!

**Comment by susheel** [comment]
@briandoconnor I have already rebased this to point to release/v2.0.1. We can bump the version before merge.

**Comment by dglazer** [comment]
@susheel, this PR is indeed set up to point to TRS release/v2.0.1 -- good.
I believe @briandoconnor is saying, and I agree, that it should also be set up to pull a specific pinned release of the service-info spec (which doesn't yet exist), so it will be stable until we consciously want to update it.

**Comment by dglazer** [comment]
Also -- I"m not finding the auto-built documentation for this release branch (i.e. the equivalent to https://ga4gh.github.io/tool-registry-service-schemas/preview/release/v2.0.1/docs/html5/), which is an inportant thing to preview before approving - does that exist somewhere? I know how the doc auto-builds work for WES and DRS; not sure if TRS works the same way. @denis-yuen may know more.

**Comment by denis-yuen** [comment]
> That being said, I think this should point to a particular release of service-info rather than develop. However, I think we're in a holding pattern until the service-info repo has a release: https://github.com/ga4gh-discovery/ga4gh-service-info/releases

Upvote :wink:   here https://github.com/ga4gh-discovery/ga4gh-service-info/issues/61

**Comment by denis-yuen** [comment]
> Also -- I"m not finding the auto-built documentation for this release branch (i.e. the equivalent to https://ga4gh.github.io/tool-registry-service-schemas/preview/release/v2.0.1/docs/html5/), which is an inportant thing to preview before approving - does that exist somewhere? I know how the doc auto-builds work for WES and DRS; not sure if TRS works the same way. @denis-yuen may know more.

Yup, 
Can see the docs [here](https://ga4gh.github.io/tool-registry-service-schemas/preview/service-info/docs/html5/#_getserviceinfo) 

The index for all types is shown as a[ table of contents](https://ga4gh.github.io/tool-registry-service-schemas/TableOfContents)

**Comment by susheel** [comment]
GA4GH service-info has just tagged their release [v1.0.0](https://github.com/ga4gh-discovery/ga4gh-service-info/releases/tag/v1.0.0) which now makes this PR valid to merge, barring any build and test errors.

**Pull request merged**
